#!/bin/bash
cd $(dirname "$BASH_SOURCE")
TMP=$(mktemp -d)
function finish {
  rm -rf "$TMP"
}
trap finish EXIT

# Read in the pbuser and pbdevice
PBUSER=$(jshon -e iden -u < user.json)
PBDEVICE=$(jshon -e iden -u < device-response.json)
# Format JSON payload
jshon -e push \
    -s "$1" -i body \
    -s "$PBUSER" -i source_user_iden \
    -s "$PBDEVICE" -i source_device_iden \
    -p \
< template/clipboard.json \
> "$TMP/clipboard.json"
# Send to api.pushbullet.com
curl --header "Access-Token: $PBTOKEN" \
     --header 'Content-Type: application/json' \
     --data-binary @"$TMP/clipboard.json" \
     --request POST \
     https://api.pushbullet.com/v2/ephemerals \
> latest-clipboard-response.json
